-- Seed data: 30 tennis drills
INSERT INTO public.drills (sport_id, name, description, category, difficulty, instructions) VALUES
('tennis', 'Flat Serve Practice', 'Practice consistent flat serves to the target box', 'serve', 'beginner', 'Focus on toss placement and racquet speed. Aim for the deep corners.'),
('tennis', 'Kick Serve Development', 'Develop the kick serve for clay court play', 'serve', 'intermediate', 'Brush up the back of the ball at a 2 oclock angle. Target theT.'),
('tennis', 'Slice Serve Target', 'Accuracy practice with slice serves', 'serve', 'beginner', 'Aim wide on the deuce court, body on the ad side.'),
('tennis', 'Two-Way Point Play', 'Develop rally patterns with directional changes', 'rally', 'intermediate', 'Start crosscourt, attack the net on the third ball.'),
('tennis', 'Inside-Out Forehand', 'Aggressive forehand from the ad side', 'rally', 'intermediate', 'Use for setting up winners or forcing short balls.'),
('tennis', 'Inside-Out Backhand', 'Open stance backhand down the line', 'rally', 'intermediate', 'Step around the ball and generate power through rotation.'),
('tennis', 'Return of Serve Deep', 'Deep blocking returns to neutralise big servers', 'rally', 'intermediate', 'Block returns deep to the corners, aim for 2 paces behind baseline.'),
('tennis', 'Approach Angles', 'Approach shots with angle variations', 'footwork', 'advanced', 'Use slice approach and vary the angles to open the court.'),
('tennis', 'Net Volley Pressure', 'Volley drills with directional goals', 'net', 'intermediate', 'Practice medium volleys with specific targets after approach.'),
('tennis', 'Overhead Smashes', 'Reaction smashes and positioning', 'net', 'beginner', 'Call loud and move under the ball quickly.'),
('tennis', 'Split Step Timing', 'Reaction drills with split step at various moments', 'footwork', 'beginner', 'Focus on timing split step before the opponent contacts.'),
('tennis', 'Lateral Movement Patterns', 'Side-to-side footwork with racquet contacts', 'footwork', 'beginner', 'Move in triangles, finish with a forehand and backhand.'),
('tennis', 'Recovery Sprint Drill', 'Sprint to ball then recover to position', 'footwork', 'intermediate', 'Coach feeds dropshots, player sprints, recovers to center.'),
('tennis', 'Drop Shot Variation', 'Disguised drop shots with recovery', 'rally', 'intermediate', 'Use neutral rally then surprise with drop shot.'),
('tennis', 'Half-Volley Control', 'Defensive half-volleys from deep position', 'rally', 'advanced', 'Touch the ball into the court, use the bounce to control.'),
('tennis', 'Tactical Pattern Play', 'Pattern-based point building', 'tactics', 'advanced', 'Play specific patterns: serve-wide, return-deep, attack-net.'),
('tennis', 'Deuce Court Patterns', 'High-percentage patterns from the deuce side', 'tactics', 'intermediate', 'Defaults: serve out wide, return crosscourt, attack the net.'),
('tennis', 'Ad Court Patterns', 'Tactical patterns from the ad side', 'tactics', 'intermediate', 'Defaults: serve T, return to backhand, rally to forehand.'),
('tennis', 'Two-On-One Doubles', 'Doubles positioning and coverage patterns', 'tactics', 'intermediate', 'Practice court coverage and communication.'),
('tennis', 'Serve-and-Volley Entry', 'Classic serve-and-volley automation', 'net', 'advanced', 'Approach the net on 80% of first serves.'),
('tennis', 'Consistency Challenge', 'Longest rally competition', 'rally', 'beginner', 'Keep rallies alive while aiming control patches.'),
('tennis', 'First Ten Balls', 'High-intensity opening sequence', 'rally', 'advanced', 'First ten balls at 100% intensity, best of 5 games.'),
('tennis', 'Crosscourt Dominance', 'Control crosscourt rallies before attack', 'rally', 'beginner', 'Win crosscourt rallies before changing direction.'),
('tennis', 'Down-the-Line Finishes', 'Passing shot accuracy under pressure', 'rally', 'advanced', 'Coach at net, player must pass with depth.'),
('tennis', 'Body Serve Returns', 'Disrupt servers with body attention', 'rally', 'intermediate', 'Return to the body to limit serve and volley options.'),
('tennis', 'Set Piece Point Play', 'Scripted 5-6 ball sequences', 'tactics', 'intermediate', 'Script patterns, debrief after each completion.'),
('tennis', 'Emotional Reset Drills', 'High-pressure points with reset targets', 'mental', 'advanced', 'Play 10 points, reset composure after each, track mental errors.'),
('tennis', 'Winner or Error Game', 'Aggressive play rules for development', 'tactics', 'intermediate', 'Winner or error in every rally, learn offensive boundaries.'),
('tennis', 'Emergency Serve Practice', 'Build second serve confidence', 'serve', 'beginner', 'Land 8/10 second serves in play during long games.'),
('tennis', 'Break Point Psychology', 'Simulated break point scenarios', 'mental', 'advanced', 'Practice execution on breakpoints, track conversion rate.');

-- Seed data: 30 padel drills
INSERT INTO public.drills (sport_id, name, description, category, difficulty, instructions) VALUES
('padel', 'Serve Zone Accuracy', 'Land serves in the correct box zones', 'serve', 'beginner', 'Serves must bounce in the correct service box, vary placement.'),
('padel', 'Return Deep', 'Deep blocking returns to control the net', 'rally', 'beginner', 'Block returns 2m behind net to neutralise net players.'),
('padel', 'Open Court Lob Defence', 'Anticipate and track lobs effectively', 'footwork', 'intermediate', 'Call and position early for lobs, overhead when possible.'),
('padel', 'Net Pressure Play', 'Build net position through controlled attacks', 'net', 'intermediate', 'Approach the net after forcing a weak return.'),
('padel', 'Glass Wall Control', 'Use walls effectively for ball control', 'rally', 'intermediate', 'Learn to let ball bounce on backwall for difficult exchanges.'),
('padel', 'Vibora Development', 'Overhead smash technique for padel', 'net', 'advanced', 'Call loud, position under the ball, snap wrist at contact.'),
('padel', 'Reves Technique', 'Backhand smash mechanics', 'net', 'advanced', 'Contact ball above head, follow through across body.'),
('padel', ' bandeja Variation', 'Controlled bandeja for defensive play', 'net', 'intermediate', 'Softer pace, drop the ball just past the net.'),
('padel', 'Lob Offense Strategy', 'When to use lobs offensively', 'tactics', 'intermediate', 'Use to move opponents deep or create space for winners.'),
('padel', 'Dink Battle', 'Touch play at the net with precision', 'net', 'advanced', 'Keep ball low, aim for the缝隙 between net and players.'),
('padel', 'Transition Game', 'Footwork between defensive and offensive', 'footwork', 'intermediate', 'Practice split step and ready position adjustments.'),
('padel', 'Partner Communication', 'Call system for court coverage', 'tactics', 'beginner', 'Establish who calls the ball, communicate early.'),
('padel', 'Wide Serve Variation', 'Exploit wide serves on deuce side', 'serve', 'intermediate', 'Angle serves wide to open court for the partner.'),
('padel', 'Winner Execution', 'Close-net putaways with angle', 'net', 'advanced', 'Use angles and speed for winning smashes.'),
('padel', 'Three-Quarter Court Play', 'Aggressive play from defensive positions', 'rally', 'advanced', 'Use three-quarter court balls to set up partners.'),
('padel', 'Sidewall Rebound Reading', 'Anticipate sidewall bounces', 'footwork', 'intermediate', 'Predict ball path after sidewall interaction.'),
('padel', 'Kick Serve Application', 'Use kick serves that bounce away', 'serve', 'intermediate', 'Serves should bounce high on the returner.'),
('padel', 'Return and Cover', 'Coverage patterns after return', 'tactics', 'intermediate', 'After return, slide into position for partner coverage.'),
('padel', 'Overhead Positioning', 'Always position best for smashes', 'footwork', 'intermediate', 'Move to center under ball, call loudly for priority.'),
('padel', 'Two-On-One Conversion', 'Turn 2-vs-1 situations to advantage', 'tactics', 'advanced', 'Use patient rally to create the 2-on-1.'),
('padel', 'Smart Risk Management', 'Calculated shot selection', 'tactics', 'intermediate', 'Know when to go for winners vs. keeping ball in play.'),
('padel', 'Forehand Power Drive', 'Aggressive forehand winners', 'rally', 'intermediate', 'Step around ball, drive through contact point.'),
('padel', 'Backhand Control', 'Steady backhand for rally building', 'rally', 'beginner', 'Contact ball out front, maintain controlled trajectory.'),
('padel', 'Bounce and Break', 'Use wall bounce to reset rally', 'rally', 'intermediate', 'Let difficult balls bounce on backwall to continue.'),
('padel', 'Match Tiebreak Simulation', 'High-pressure tiebreak scenarios', 'mental', 'advanced', 'Practice under pressure, track decision-making.'),
('padel', 'Ace Target Practice', 'Planned ace serving zones', 'serve', 'advanced', 'Map specific targets for ace serves in key moments.'),
('padel', 'Unforced Error Reduction', 'Discipline in high-risk situations', 'tactics', 'intermediate', 'Track unforced errors, focus on high-percentage play.'),
('padel', 'Court Coverage Patterns', 'Systematic movement and positioning', 'footwork', 'beginner', 'Learn zones, rotate through coverage systematically.'),
('padel', 'Wrist Snap Technique', 'Generate power through wrist snap', 'net', 'advanced', 'Follow through across body, snap wrist at contact.'),
('padel', 'Psychological Presence', 'Composed play under pressure', 'mental', 'advanced', 'Breathe, reset between points, maintain focus.');

-- Seed data: 20 drills for other sports
INSERT INTO public.drills (sport_id, name, description, category, difficulty, instructions) VALUES
('badminton', 'Short Serve Precision', 'Drop serves that land close to net', 'serve', 'beginner', 'Toss low, contact ball early, push forward.'),
('badminton', 'Clear Deep', 'High clears to the back of the court', 'rally', 'beginner', 'Clear to the rear corners, hold the rally.'),
('badminton', 'Smash Defence', 'Deflect smashes with control', 'rally', 'intermediate', 'Drive smashes back, aim for deep areas.'),
('badminton', 'Net Drop Recovery', 'Drop shots with recovery positioning', 'rally', 'intermediate', 'Drop to net, recover to center quickly.'),
('badminton', 'Footwork Patterns', 'Multi-directional movement drills', 'footwork', 'beginner', 'Practice 8-point footwork patterns at speed.'),
('squash', 'Serve Deep Target', 'Land serves deep in the service box', 'serve', 'beginner', 'Serve deep, follow to theT position.'),
('squash', 'Crosscourt Rally', 'Control crosscourt exchanges', 'rally', 'beginner', 'Keep ball tight to sidewalls, maintain depth.'),
('squash', 'Boast Control', 'Three-wall boast execution', 'rally', 'intermediate', 'Use boast to set up attacks, learn angles.'),
('squash', 'Short Game Touch', 'Drop shots and volleys', 'net', 'intermediate', 'Drop volley to front corner, follow toT.'),
('squash', 'Retrieving Fitness', 'Long rally survival drills', 'footwork', 'advanced', 'Play extended rallies, focus on movement economy.'),
('table_tennis', 'Serve Variation', 'Curse serve with spin variations', 'serve', 'intermediate', 'Hide contact, vary spin direction and speed.'),
('table_tennis', 'Loop Attack Drill', 'Topspin loop execution', 'rally', 'intermediate', 'Loop from half-distance, close out points.'),
('table_tennis', 'Block Consistency', 'Blocking against topspin', 'rally', 'intermediate', 'Block with angle, absorb pace, keep ball deep.'),
('table_tennis', 'Flick Technique', 'Table-level flick against short serves', 'serve', 'advanced', 'Contact ball at highest point, generate topspin.'),
('table_tennis', 'Third Ball Attack', 'Attack-oriented serving patterns', 'tactics', 'intermediate', 'Serve to lead to third-ball attack opportunities.'),
('running_100m', 'Block Start Explosiveness', 'Explosive starts from blocks', 'footwork', 'beginner', 'Drive hard on first 3 steps, maintain posture.'),
('running_100m', 'Top-End Speed', 'Speed maintenance over 60-80m', 'footwork', 'intermediate', 'Run flyINS at 95% for 60m flying start.'),
('running_100m', 'Finish Mechanics', 'Proper lean and finish technique', 'footwork', 'beginner', 'Lean at line, chest first, full extension.'),
('pickleball', 'Third Shot Drop', 'Reset drops from deep position', 'rally', 'intermediate', 'Dink third shot deep, approach net.'),
('pickleball', 'Dink Control', 'Kitchen-line dinking with accuracy', 'net', 'intermediate', 'Crosscourt dinks, aim for opponent feet.');

-- Seed additional well-known sports with a base set
INSERT INTO public.drills (sport_id, name, description, category, difficulty, instructions) VALUES
('basketball', 'Free Throw Routine', 'Consistent free throw form and routine', 'shooting', 'beginner', 'Same routine every time, follow through smoothly.'),
('basketball', 'Three-Point Shooting', 'Spot-up three-point accuracy', 'shooting', 'intermediate', 'Square shoulders, high release, consistent arc.'),
('basketball', 'Layup Footwork', 'Game-speed layup connections', 'footwork', 'beginner', 'Two-foot gather, power foot takeoff, soft finish.'),
('soccer', 'Passing Accuracy', 'Ground passing with both feet', 'passing', 'beginner', 'Passes on ground, aim for feet of teammate.'),
('soccer', 'Shooting Drill', 'MedIOC passes leading to shots', 'shooting', 'intermediate', 'Receive in stride, strike on target.');
